# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('pwd', models.CharField(max_length=18)),
                ('sex', models.CharField(default='', max_length=5)),
                ('age', models.IntegerField(default=0)),
                ('por', models.ImageField(default='', upload_to=b'')),
                ('email', models.CharField(max_length=20)),
                ('tel', models.CharField(default='', max_length=15)),
                ('property', models.IntegerField(default=10)),
            ],
        ),
    ]
