# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoveHelp', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
