# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoveHelp', '0003_auto_20170122_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='id',
            new_name='num',
        ),
    ]
