# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoveHelp', '0004_auto_20170122_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='addr',
        ),
    ]
