# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoveHelp', '0005_remove_event_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='publish_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='receive_time',
            field=models.DateTimeField(null=True),
        ),
    ]
