# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoveHelp', '0008_auto_20170214_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='por',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
