# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoveHelp', '0020_auto_20170302_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_Img',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='money',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='receiver',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
