# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoveHelp', '0021_auto_20170302_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
