# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoveHelp', '0022_auto_20170302_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_Img',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='money',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_status',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rec_status',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='event',
            name='receiver',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(default='false', max_length=10),
        ),
    ]
